### ISSUE TITLE
Code structure

### ISSUE THREAD

**Issue by burrt** [shiyuechengineer/meraki-dashboard#2]
Hey,

I was just curious if you ever thought about splitting the code so it's more organized?
You can always group the API calls into modules similar to the documentation - makes it easier for someone to read, debugging, extending etc.

I haven't ran your code since I didn't see this until too late...

Other minor improvements you could make:
* doc string consistency - for pydoc etc.
* fixing links to API docs `https://dashboard.meraki.com/api_docs`

Great work though haha, can't say I would be bothered to write all of this.

**Comment by shiyuechengineer** [comment]
All good suggestions... probably something to think of for the next major revamp!
